name: Run Playwright Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright adapter
        run: npm install -D allure-playwright

      - name: Install Allure CLI globally
        run: npm install -g allure-commandline --save-dev

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report