name: Run Playwright Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure globally
        if: github.ref == 'refs/heads/main'
        run: npm install -g allure-commandline

      - name: Run tests
        run: npm run test:allure

      - name: Upload Allure report
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

      - name: Generate Allure report
        if: github.ref == 'refs/heads/main'
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
      - name: Clean up Allure results
        if: github.ref == 'refs/heads/main'
        run: rm -rf ./allure-results ./allure-report