name: Run Playwright Tests and Generate HTML Report

on:
  push:

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npx playwright test --reporter=html || true
      - uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
          retentionDays: 30

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report