name: Run Playwright Tests with Allure

on: [push]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test

      - name: Generate Allure report
        run: npm run test:allure

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
