name: Run Playwright Tests with Allure

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure commandline
        run: |
          npm install -D allure-playwright
          npm install -g allure-commandline --save-dev

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report
        if: github.ref == 'refs/heads/main'
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report