name: Run Playwright Tests with Allure

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npx playwright install --with-deps
      - run: |
          npm install -D allure-playwright
          npm install -g allure-commandline --save-dev
      - run: |
          npx playwright test --reporter=line,allure-playwright || true
          allure generate allure-results --clean -o allure-report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
