name: Run Playwright Tests with Allure

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure dependencies
        run: |
          npm install -D allure-playwright
          npm install -g allure-commandline --save-dev

      - name: Run Playwright tests
        run: bash -c "npx playwright test --reporter=line,allure-playwright || true"

      - name: Generate Allure report
        run: bash -c "allure generate allure-results --clean -o allure-report"

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
