name: Run Playwright Tests and Generate HTML Report

on:
  push:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npx playwright test --reporter=html || true
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retentionDays: 30

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report