name: Run Playwright Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install browsers
        run: npx playwright install
      - name: Run tests
        run: npm run test:allure
      - name: Generate Allure report
        run: npm run allure:generate
        continue-on-error: true
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Allure report
          path: ./allure-report
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Allure results
          path: ./allure-results